export const galleries = [
    {
        id: 'pertemuan-perdana-kelompok-peru',
        title: 'Pertemuan Perdana Kelompok Peru',
        date: 'Minggu, 1 September 2024',
        thumbnail: '/img/gallery/01-09-2024/thumbnail.jpg',
        photos: Array.from(
            { length: 27 },
            (_, i) => `/img/gallery/01-09-2024/19${i + 1}.jpg`
        ),
        location: {
            name: 'Mokopi Jalur',
            url: '',
        },
        keywords: [
            'This Is Peru',
            'Galeri Kelompok Peru',
            'Galeri Kelompok Peru 45',
            'We Are Peru',
            'Peru 45',
            'Mabim Nusa Putra',
            'Maba Nusa Putra',
            'Mahasiswa Baru Nusa Putra',
            'Kelompok Peru',
            'Kelompok Peru Nusa Putra',
            'This Is Peru 45',
            'This Is Peru Pride',
            'Pertemuan Perdana Kelompok Peru',
        ],
        created_at: '2024-09-01T00:00:00',
    },
    {
        id: 'pembuatan-atribut-kelompok-peru',
        title: 'Pembuatan Atribut Kelompok Peru',
        date: 'Selasa, 3 September 2024',
        thumbnail: '/img/gallery/03-09-2024/thumbnail.jpg',
        photos: Array.from(
            { length: 6 },
            (_, i) => `/img/gallery/03-09-2024/39${i + 1}.jpg`
        ),
        location: {
            name: 'Mokopi Jalur',
            url: '',
        },
        keywords: [
            'This Is Peru',
            'Galeri Kelompok Peru',
            'Galeri Kelompok Peru 45',
            'We Are Peru',
            'Peru 45',
            'Mabim Nusa Putra',
            'Maba Nusa Putra',
            'Mahasiswa Baru Nusa Putra',
            'Kelompok Peru',
            'Kelompok Peru Nusa Putra',
            'This Is Peru 45',
            'This Is Peru Pride',
            'Proses Shooting Tugas Kelompok Peru',
        ],
        created_at: '2024-09-03T00:00:00',
    },
    {
        id: 'proses-shooting-tugas-kelompok-peru',
        title: 'Proses Shooting Tugas Kelompok Peru',
        date: 'Rabu, 4 September 2024',
        thumbnail: '/img/gallery/04-09-2024/thumbnail.JPG',
        photos: Array.from(
            { length: 40 },
            (_, i) => `/img/gallery/04-09-2024/49${i + 1}.JPG`
        ),
        location: {
            name: 'Situ Gunung',
            url: '',
        },
        keywords: [
            'This Is Peru',
            'Galeri Kelompok Peru',
            'Galeri Kelompok Peru 45',
            'We Are Peru',
            'Peru 45',
            'Mabim Nusa Putra',
            'Maba Nusa Putra',
            'Mahasiswa Baru Nusa Putra',
            'Kelompok Peru',
            'Kelompok Peru Nusa Putra',
            'This Is Peru 45',
            'This Is Peru Pride',
            'Proses Shooting Tugas Kelompok Peru',
        ],
        created_at: '2024-09-04T00:00:00',
    },
    {
        id: 'produksi-konten-kelompok-peru',
        title: 'Produksi Konten Kelompok Peru',
        date: 'Jumat, 6 September 2024',
        thumbnail: '/img/gallery/06-09-2024/thumbnail.jpg',
        photos: Array.from(
            { length: 10 },
            (_, i) => `/img/gallery/06-09-2024/69${i + 1}.jpg`
        ),
        location: {
            name: 'Basecamp Kelompok Peru',
            url: '',
        },
        keywords: [
            'This Is Peru',
            'Galeri Kelompok Peru',
            'Galeri Kelompok Peru 45',
            'We Are Peru',
            'Peru 45',
            'Mabim Nusa Putra',
            'Maba Nusa Putra',
            'Mahasiswa Baru Nusa Putra',
            'Kelompok Peru',
            'Kelompok Peru Nusa Putra',
            'This Is Peru 45',
            'This Is Peru Pride',
            'Produksi Konten Kelompok Peru',
        ],
        created_at: '2024-09-06T00:00:00',
    },
    {
        id: 'mabim-hari-pertama',
        title: 'Mabim Hari Pertama',
        date: 'Senin, 9 September 2024',
        thumbnail: '/img/gallery/09-09-2024/thumbnail.jpeg',
        photos: Array.from(
            { length: 25 },
            (_, i) => `/img/gallery/09-09-2024/99${i + 1}.jpeg`
        ),
        location: {
            name: 'Universitas Nusa Putra',
            url: '',
        },
        keywords: [
            'This Is Peru',
            'Galeri Kelompok Peru',
            'Galeri Kelompok Peru 45',
            'We Are Peru',
            'Peru 45',
            'Mabim Nusa Putra',
            'Maba Nusa Putra',
            'Mahasiswa Baru Nusa Putra',
            'Kelompok Peru',
            'Kelompok Peru Nusa Putra',
            'This Is Peru 45',
            'This Is Peru Pride',
            'Mabim Hari Pertama',
            'Mabim Nusa Putra Hari Pertama',
            'Mabim Hari Ke-1',
        ],
        created_at: '2024-09-09T00:00:00',
    },
    {
        id: 'mabim-hari-kedua',
        title: 'Mabim Hari Kedua',
        date: 'Selasa, 10 September 2024',
        thumbnail: '/img/gallery/10-09-2024/thumbnail.jpeg',
        photos: Array.from(
            { length: 17 },
            (_, i) => `/img/gallery/10-09-2024/109${i + 1}.jpeg`
        ),
        location: {
            name: 'Universitas Nusa Putra',
            url: '',
        },
        keywords: [
            'This Is Peru',
            'Galeri Kelompok Peru',
            'Galeri Kelompok Peru 45',
            'We Are Peru',
            'Peru 45',
            'Mabim Nusa Putra',
            'Maba Nusa Putra',
            'Mahasiswa Baru Nusa Putra',
            'Kelompok Peru',
            'Kelompok Peru Nusa Putra',
            'This Is Peru 45',
            'This Is Peru Pride',
            'Mabim Hari Kedua',
            'Mabim Nusa Putra Hari Kedua',
            'Mabim Hari Ke-2',
        ],
        created_at: '2024-09-10T00:00:00',
    },
    {
        id: 'mabim-hari-ketiga',
        title: 'Mabim Hari Ketiga',
        date: 'Rabu, 11 September 2024',
        thumbnail: '/img/gallery/11-09-2024/thumbnail.jpeg',
        photos: Array.from(
            { length: 7 },
            (_, i) => `/img/gallery/11-09-2024/119${i + 1}.jpeg`
        ),
        location: {
            name: 'Universitas Nusa Putra',
            url: '',
        },
        keywords: [
            'This Is Peru',
            'Galeri Kelompok Peru',
            'Galeri Kelompok Peru 45',
            'We Are Peru',
            'Peru 45',
            'Mabim Nusa Putra',
            'Maba Nusa Putra',
            'Mahasiswa Baru Nusa Putra',
            'Kelompok Peru',
            'Kelompok Peru Nusa Putra',
            'This Is Peru 45',
            'This Is Peru Pride',
            'Mabim Hari ketiga',
            'Mabim Nusa Putra Hari ketiga',
            'Mabim Hari Ke-3',
        ],
        created_at: '2024-09-11T00:00:00',
    },
]
